name: publish :rocket:

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-lastest

    steps:
      - uses: action/checkout@v3

      - name: Setup .NET
        uses: action/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./GitHubAction.csproj

      - name: Build
        run: dotnet build ./GitHubAction.csproj -- configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./GitHubAction.csproj -- configuration Release --no-build
          
